name: dotnet format

on: 
  pull_request:
    branches: ["master"]
  push:
    branches: ["master", "TestBranch"]

jobs:
  check-format:
    runs-on: windows-latest
    steps:
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
          with:
          dotnet-version: '8.0.x'
       
      - name: Check out code
        uses: actions/checkout@v3
       
      - name: Run dotnet format
        run: dotnet format --no-restore --verify-no-changes

